services:
  translate:
    build: .
    container_name: Gemini-Translate
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MODELAI=${MODELAI}
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
